### ISSUE TITLE
I can't see icons

### ISSUE THREAD

**Issue by MicheleFiladelfia** [ecosse3/nvim#85] opened 2022-08-18 11:33 UTC
![screenshot](https://user-images.githubusercontent.com/86882607/185384992-b5781b5f-e695-4f04-8e37-ebb8bd9db9dd.png)
as you can see, instead of icons it shows me random icons

**Comment by ecosse3** [comment] 2022-08-18 11:38
Duplicate of #72.

**Closed by ecosse3** 2022-08-18 11:38 UTC
Labels: duplicate, configuration
